music.play(music.tonePlayable(698, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
music.play(music.tonePlayable(587, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
music.play(music.tonePlayable(523, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
music.play(music.tonePlayable(466, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
music.play(music.tonePlayable(523, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(466, music.beat(BeatFraction.Double))
